#!/bin/bash
# Generate SSL certificate using Let's Encrypt for webphone.insightintelligence.io
# This script will use HTTP-01 validation through a temporary HTTP server

set -e

DOMAIN="webphone.insightintelligence.io"
CERT_DIR="./ssl-certs"
EMAIL="drchiniquy@gmail.com"

echo "=== Generating SSL Certificate for $DOMAIN ==="
echo "This will use HTTP-01 challenge. The domain must be pointing to this machine."
echo "Current domain resolution:"
nslookup $DOMAIN || echo "DNS resolution failed"

# Create certificate directory
mkdir -p $CERT_DIR

# Check if certbot is installed
if ! command -v certbot &> /dev/null; then
    echo "Certbot not found. Installing..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Run: brew install certbot"
        echo "Then run this script again."
        exit 1
    else
        sudo apt-get update && sudo apt-get install -y certbot
    fi
fi

echo "Using DNS-01 challenge method..."
echo "You'll need to create a DNS TXT record as instructed."
echo "Press Enter to continue..."
read

# Generate certificate using DNS validation (manual)
sudo certbot certonly \
    --manual \
    --preferred-challenges dns \
    --email $EMAIL \
    --agree-tos \
    --no-eff-email \
    -d $DOMAIN

# Copy certificates to our directory for easier access
CERT_PATH="/etc/letsencrypt/live/$DOMAIN"
sudo cp "$CERT_PATH/fullchain.pem" "$CERT_DIR/certificate.pem"
sudo cp "$CERT_PATH/privkey.pem" "$CERT_DIR/private.pem" 
sudo cp "$CERT_PATH/chain.pem" "$CERT_DIR/ca.pem"

# Make files readable
sudo chown $(whoami):$(whoami) "$CERT_DIR"/*
chmod 600 "$CERT_DIR/private.pem"
chmod 644 "$CERT_DIR/certificate.pem" "$CERT_DIR/ca.pem"

echo "=== Certificate files generated ==="
echo "Certificate: $CERT_DIR/certificate.pem"
echo "Private Key: $CERT_DIR/private.pem" 
echo "CA Chain: $CERT_DIR/ca.pem"

echo ""
echo "=== Creating Terraform Variables File ==="

# Create terraform variables file with certificate contents
cat > ssl-certificates.tfvars << EOF
# SSL Certificate generated by Let's Encrypt
ssl_certificate = <<EOT
$(cat $CERT_DIR/certificate.pem)
EOT

ssl_private_key = <<EOT
$(cat $CERT_DIR/private.pem)
EOT

ssl_ca_certificate = <<EOT
$(cat $CERT_DIR/ca.pem)
EOT
EOF

echo "Created ssl-certificates.tfvars with certificate contents."
echo ""
echo "Next steps:"
echo "1. Run: terraform apply -var-file=ssl-certificates.tfvars"
echo "2. Test HTTPS: curl https://$DOMAIN"